# Site settings
title: Your First Pull Request
description: >
  Your First PR helps you get started contributing to Open Source by showcasing great starter issues on Github and elsewhere.

baseurl: ""
url: "http://yourfirstpr.github.io/"

# default site author info
author: Charlotte Spencer
name: Your First PR

# don't build repo only files
exclude: ["README.md", "CODEOFCONDUCT.md"]

# pagination

paginate: 4
paginate_path: "/blog/:num/"
